config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'

  post 'register/user_creation' => 'home#register_new_user', as: :registration_form
  get 'register/user' => 'home#register', as: :new_user_registration_path
  get 'user/login' => 'home#login', as: :new_user_session_path

  get 'movies' => 'movies#index'
  get 'movies/:id' => 'movies#screens', as: :movie_screens_path
  get 'booking/:id' => 'ticket#booking', as: :booking_path
  post 'booking/:id' => 'ticket#book_ticket', as: :book_ticket_path
  get 'booking/cancel/:id' => 'ticket#cancel_ticket', as: :cancel_booking

  get 'user/bookings' => 'home#bookings', as: :user_bookings

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    movies = Movie.fetch_movies
    @movies = format_movie_list(movies)
  end

  def screens
    movie_screen_info = Movie.fetch_movie_screens(params[:id])
    @movie_screens = format_movie_screens_list(movie_screen_info)
    puts @movie_screens
  end

  private

  def format_movie_list(movies)
    movie_info = []
    movies.each do |movie|
      movie_info <<
          {
          id: movie.id,
          name: movie.name,
          fee: movie.ticket_fee,
          language: Movie::LANGUAGE.invert[movie.language],
          currency: Movie::CURRENCY.invert[movie.currency],
          crew: movie.crew_info
      }
    end
    movie_info
  end

  def format_movie_screens_list(movie_screen_info)
    movie_screens = movie_screen_info[:movie_screens]
    show_info = movie_screen_info[:show_info]
    theater_screen = {}
    movie_screens.each do |movie_screen|
      theater = Theater.find_by(id: movie_screen.theater_id)
      theater_screen[theater.id] ||= {theater_name: theater.name, theater_city: theater.city}
      (theater_screen[theater.id][:show_times] ||= []) << {
          movie_name: movie_screen_info[:movie_name],
          movie_fee: movie_screen_info[:ticket_fee],
          show_time: show_info[movie_screen.show_id].show_time,
          show_date: movie_screen.show_date,
          remaining_seats: movie_screen.remaining_seats,
          total_capacity: movie_screen.total_seats,
          movie_screen_id: movie_screen.id
      }
    end
    return theater_screen
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
    <p>Current movies shown</p>
    <div class="movies_list">


      <% @movies.each do |movie| %>
        <h3> Movie :: <%= movie[:name]%></h3>
          <span><b>Language</b> <%= movie[:language]%></span>
          <div class="row">
            <div class="col-xs-6 col-md-4">
              <%= movie[:crew]%>
            </div>
            <div class="col-xs-6 col-md-4">
              <b>Price</b>: <%= movie[:currency]%> <%=movie[:fee]%>
            </div>
            <div class="col-xs-12 col-md-4">
              <a href =<%= movie_screens_path_url(movie[:id])%>>
                <div class="btn btn-primary">Screens</div>
              </a>
            </div>
          </div>
      <%end%>
    </div>
  </div>
</div>

app/views/movies/screens.html.erb
<div class="jumbotron">
  <div class="container">
    <p>Screens showing <%= @movie_screens.first.second[:show_times].first[:movie_name]%></p>
    <div class="theater_list">
      <% @movie_screens.each do |_,theater| %>
          <h3> <%= theater[:theater_name]%> , <%= theater[:theater_city]%></h3>
          <% theater[:show_times].each do |show|%>
              <div><b>Date</b> <%= show[:show_date]%></div>
              <div class="row">
                <div class="col-xs-4 col-md-3">
                  Time <%= show[:show_time].strftime("%H:%M:%S")%>
                </div>
                <div class="col-xs-4 col-md-3">
                  Seats <%= show[:remaining_seats]%> (Total :<%= show[:total_capacity] %>)
                </div>
                <div class="col-xs-4 col-md-3">
                  Price <%= show[:movie_fee]%>
                </div>
                <div class="col-xs-12 col-md-3">
                  <%if MovieScreen.valid_to_book(show[:movie_screen_id])%>
                      <a href= <%="/booking/#{show[:movie_screen_id]}"%>>
                      <button type="button" class="btn btn-primary" style="width: 100%;color:white;"> Book </button></a>
                  <%else%>
                      <div style="height: 40px; line-height: 40px; background-color: lightgrey; text-align: center; border: 1px solid;">Ended!</div>
                  <%end%>
                </div>
              </div>
          <%end%>
      <%end%>
    </div>
  </div>
</div>