config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'

  post 'register/user_creation' => 'home#register_new_user', as: :registration_form
  get 'register/user' => 'home#register', as: :new_user_registration_path
  get 'user/login' => 'home#login', as: :new_user_session_path

  get 'movies' => 'movies#index'
  get 'movies/:id' => 'movies#screens', as: :movie_screens_path
  get 'booking/:id' => 'ticket#booking', as: :booking_path
  post 'booking/:id' => 'ticket#book_ticket', as: :book_ticket_path
  get 'booking/cancel/:id' => 'ticket#cancel_ticket', as: :cancel_booking

  get 'user/bookings' => 'home#bookings', as: :user_bookings

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def register
  end

  def login
    puts params
    # current_user = User.find_by(email:params[])
  end

  def register_new_user
    puts "params"
    puts params
    User.create_new_user(params[:user])
    redirect_to "/users/sign_in"
  end

  def bookings
    if current_user.present?
      @ticket_array = Ticket.fetch_user_tickets(current_user.id)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bookings.html.erb
<div class="jumbotron">
  <div class="container">
    <p>Tickets booked</p>
    <div class="ticket_list">
      <% @ticket_array.each do |ticket| %>
          <h4>Ticket no: <%= ticket[:id]%></h4>
          <div class="row">
            <h5> Movie Info </h5>
            <div class="col-md-3">
             <span><b> Movie</b> <%= ticket[:movie]%></span>
            </div>
            <div class="col-md-3">
             <span><b> Language</b> <%= ticket[:language]%></span>
            </div>
            <div class="col-md-3">
             <span><b> Seats</b> <%= ticket[:seats]%></span>
            </div>
          </div>

          <div class="row">
            <h5> Theater Info </h5>
            <div class="col-md-3">r
             <span><b>Theater</b> <%= ticket[:theater_name]%>,<%= ticket[:theater_city]%> </span>
            </div>
            <div class="col-md-3">
             <span><b> Show time</b> <%= ticket[:show_time].strftime("%H:%M:%S")%></span>
            </div>
            <div class="col-md-3">
             <span><b> Amount</b> <%= ticket[:amount]%></span>
            </div>
            <div class="col-xs-6 col-md-3">
              <%if ticket[:active] %>
                  <a href="<%=cancel_booking_path(ticket[:id])%>">
                  <button type="button" class="btn btn-danger" style="width: 100%;color: white;">Cancel</button>
                  </a>
              <%else%>
                  <div style="height: 40px; line-height: 40px; background-color: lightgrey; text-align: center; border: 1px solid;">Cancelled!</div>
            <%end%>
            </div>
          </div>

          <br><br><br>

      <%end%>
    </div>
  </div>
</div>

app/views/home/index.html.erb
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome!</h1>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>

app/views/home/register.html.erb
<h2>Sign up</h2>

<%= form_for(:user, url: registration_form) do |f| %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>


    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name%>
    </div>

    <div class="field">
      <%= f.label :gender %><br />
      <%= f.text_field :gender%>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
<% end %>

<%= render "devise/shared/links" %>