config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'

  post 'register/user_creation' => 'home#register_new_user', as: :registration_form
  get 'register/user' => 'home#register', as: :new_user_registration_path
  get 'user/login' => 'home#login', as: :new_user_session_path

  get 'movies' => 'movies#index'
  get 'movies/:id' => 'movies#screens', as: :movie_screens_path
  get 'booking/:id' => 'ticket#booking', as: :booking_path
  post 'booking/:id' => 'ticket#book_ticket', as: :book_ticket_path
  get 'booking/cancel/:id' => 'ticket#cancel_ticket', as: :cancel_booking

  get 'user/bookings' => 'home#bookings', as: :user_bookings

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieTickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Movie Tickets', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Bookings', user_bookings_path%></li>
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <li> <%= current_user.name %> </li>
        <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>